<?php
/**
 * @package     Team Ode To Code
 * @author      Codilar Technologies
 * @license     https://opensource.org/licenses/OSL-3.0 Open Software License v. 3.0 (OSL-3.0)
 * @link        http://www.codilar.com/
 */

/** @var Codilar\B2bSpace\Block\B2bSpace $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
$messageData = $block->getMessageData();
$customerId = $block->getCustomerId();
$company = $block->getCompany();
$users = $block->getCompanyUsers($company->getId());
?>
<div class="head"><h2><?= $escaper->escapeHtml($company->getCompanyName())?></h2></div>
<div class="header-text">
    <div class="block block-message-search">
        <div class="block-content">
            <div class="message-searchbox">
                <form>
                    <div class="field search">
                        <div class="control">
                            <input id="message-search" type="text" class="input-text message-search form-control input-query ui-autocomplete-input" name="search-query"
                                   placeholder="<?= /** @noEscape */ __('Search Message…') ?>">
                            <div class="autocomplete-suggestions"></div>
                            <div class="no-results-found">
                                <span class="no-results-found"><?= $escaper->escapeHtml(__('No Results Found')) ?></span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <button class="view-all-members"><?= $escaper->escapeHtml(__('View All Members'))?></button>
</div>
<div class="b2bspace-main">
    <div class="b2b-messages">
        <div>
            <?php if (count($messageData) > 0): ?>
                <?php foreach ($messageData as $message): ?>
                    <div id="<?= $message->getEntityId() ?>" class="b2b_message <?= $message->getCustomerId() == $customerId ? 'right' : 'left' ?>">
                        <div class="label"><?= $escaper->escapeHtml($message->getCustomerName())?></div>
                        <div class="value"><?= $message->getMessage() ?></div>
                        <?php if ($message->getCustomerId() == $customerId): ?>
                            <button><span class="delete-message"><?= $escaper->escapeHtml(__('Delete'))?></span></button>
                        <?php endif; ?>
                    </div>
                <?php endforeach;?>
            <?php else: ?>
                <div class="nomessages"><?= $escaper->escapeHtml(__('No Messages'))?></div>
            <?php endif; ?>
        </div>
    </div>
    <div class="message-input-div">
        <form class="message-form" id="message-form">
            <label>
                <input class="message-input" name="message" type="text" placeholder="Enter the message">
            </label>
        </form>
        <button><div class="message-submit"><?= $escaper->escapeHtml(__('Send'))?></div></button>
    </div>
</div>
<div class="company-members" id="company-members">
    <?php foreach ($users as $user): ?>
        <div class="members-name"><span><?= $escaper->escapeHtml(__($user['name']))?></span></div>
        <div class="member-email"><span><?= $escaper->escapeHtml(__($user['email']))?></span></div>
    <?php endforeach; ?>
</div>
