<?php
/** @var Codilar\B2bSpace\Block\B2bSpace $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
$messageData = $block->getMessageData();
$customerId = $block->getCustomerId();
?>
<div class="b2b-messages">
    <?php foreach ($messageData as $message): ?>
        <div class="<?= $message->getCustomerId() == $customerId ? 'right' : 'left' ?>"> <?= $message->getMessage() ?></div>
    <?php endforeach;?>
</div>
