<?php
/** @var Codilar\B2bSpace\Block\B2bSpace $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
$messageData = $block->getMessageData();
$customerId = $block->getCustomerId();
?>
<div class="b2b-messages">
    <?php if (count($messageData)>0): ?>
        <?php foreach ($messageData as $message): ?>
            <div id="<?= $message->getEntityId() ?>" class="b2b_message <?= $message->getCustomerId() == $customerId ? 'right' : 'left' ?>">
                <div class="label"><?= $escaper->escapeHtml($message->getCustomerName())?></div>
                <div class="value"><?= $message->getMessage() ?></div>
            </div>
        <?php endforeach;?>
    <?php else: ?>
        <div class="nomessages"><?= $escaper->escapeHtml(__('No Messages'))?></div>
    <?php endif; ?>
</div>
